skills_list = [
    "Spring Boot",
    "Java programming",
    "Python programming",
    "Django",
    "Flask",
    "NumPy",
    "pandas",
    "Matplotlib",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Keras",
    "OpenCV",
    "SQL",
    "Data analysis",
    "Machine learning",
    "Artificial intelligence",
    "Web development",
    "Mobile development",
    "Cloud computing",
    "Database management",
    "Java",
    "Python",
    "JavaScript",
    "C++",
    "HTML",
    "CSS",
    "Linux",
    "Agile development",
    "Git",
    "Data structures and algorithms",
    "Object-oriented programming",
    "RESTful web services",
    "MVC architecture",
    "JIRA",
    "Node.js",
    "React",
    "AngularJS",
    "MongoDB",
    "AWS",
    "Azure",
    "DevOps",
    "Docker",
    "Kubernetes",
    "Continuous integration and deployment",
    "Testing frameworks (e.g. JUnit, pytest)",
    "Microservices architecture",
    "Big Data technologies (e.g. Hadoop, Spark)",
    "Machine learning",
    "Artificial intelligence",
    "Natural language processing",
    "Computer vision",
    "Neural networks",
    "Deep learning",
    "Data visualization",
    "Web development frameworks (e.g. Django, Flask)",
    "Version control systems (e.g. Git, SVN)",
    "Agile software development",
    "Scrum",
    "Kanban",
    "Lean software development",
    "Software design patterns",
    "Code review processes",
    "Database design and management",
    "Backend development",
    "Frontend development",
    "UI/UX design",
    "Mobile development",
    "Cloud computing",
]
