skills_list = [
    "Java programming",
    "Python programming",
    "Django",
    "Flask",
    "NumPy",
    "pandas",
    "Matplotlib",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Keras",
    "OpenCV",
    "SQL",
    "Data analysis",
    "Machine learning",
    "Artificial intelligence",
    "Web development",
    "Mobile development",
    "Cloud computing",
    "Database management",
    "Civil Engineering Construction",
    "Construction Management",
    "AutoCAD",
    "Engineering Project Planning",
    "Microsoft",
    "Project Contract Management",
    "Revit",
    "Project Management",
    "Project Engineering",
    "Structural Engineering",
    "Microsoft Access",
    "Concrete",
    "Mechanics of Materials",
    "Thermodynamics",
    "Fluid Mechanics",
    "Heat Transfer",
    "Materials Science",
    "Dynamics and Control Systems",
    "Machine Design",
    "Manufacturing Processes",
    "Computer-Aided Design and Drafting (CADD)",
    "Engineering Graphics and Visualization",
    "Electrical and Electronic Systems",
]
